<?php

namespace Doc\StoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * clientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clientRepository extends EntityRepository
{
	public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM DocStoreBundle:client p ORDER BY p.firstName ASC')
            ->getResult();
    }
}
