<?php
//src/Doc/StoreBundle/Repository/receptionRepository.php
namespace Doc\StoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * receptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class receptionRepository extends EntityRepository
{
	public function findReception()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM DocStoreBundle:reception p WHERE p.id = :id')->setParameter('id', 1)
            ->getResult();


    }
}
