<?php
// src/My/TestBundle/Repository/receptionRepository.php

namespace My\TestBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * receptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class receptionRepository extends EntityRepository
{
	public function findReception()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM MyTestBundle:reception p WHERE p.id = :id')->setParameter('id', 1)
            ->getResult();


    }

    public function findAllReception()
    {
    	return $this->getEntityManager()
    		->createQuery('SELECT v FROM MyTestBundle:reception v')
    		->getResult();
    }
}
